### PR TITLE
Update open-api.md

### PR DESCRIPTION
**Pull request by nick-wireless**
Food for thought... about proposed name.

Sorry... not exactly sure how best to pass on thoughts... I provided an edit for Nuxt team to consider thinking, not to be adopted in the actual code base necessarily.

### CODE REVIEW

**Comment by nick-wireless** [comment]
Also... SimpleAPI... meaning keeping things simple for a quick start (also... a small sub-set of important commands).

**Comment by nick-wireless** [comment]
Actually... thinking more about the purpose of the Hub... streamlining and simplifying coding the connection between app and services... I revert to CarbonAPI.  In my mind **if** the Hub allowed (a) seeding of backend, then (b) allowing that template to be adapted by particular user to stamp on other projects... this leads to a 'carbon copy' type API idea in my mind.

**Comment by atinux** [comment]
I can understand the confusion but Open API exists way before than Open AI

https://en.wikipedia.org/wiki/Open_API

**Comment by nick-wireless** [comment]
Oh... now I understand, thank.

**Pull request closed without merging**
