### PR TITLE
feat: add pkg.pr.new

### PR DESCRIPTION
**Pull request by Aslemammad**
A debugging session for nuxt hub!

### CODE REVIEW

**Comment by farnabaz** [comment]
@Aslemammad autofix ci is failing

**Comment by Aslemammad** [comment]
yea i'm experimenting and debugging pkg.pr.new at the same time 😅

**Comment by Aslemammad** [comment]
let's try this time!

**Comment by Atinux** [comment]
Why changing the `prepack` command @Aslemammad ?

**Comment by Aslemammad** [comment]
The reason is that when we json parse the output of npm pack, it has the address of the tarball. But when using the prepack hook we're adding output to the default json ouput of `npm pack --json` and that breaks the parsing.

I'm trying to verify my assumptions! let me know what do you think.

**Comment by Aslemammad** [comment]
just pushed a new update, can we try now? sorry for disturbing!

**Comment by Aslemammad** [comment]
I guess this is working now! I'll try to find a way to support packing hooks like prepack in pkg.pr.new, but it might be complicated. let's see.

meanwhile, we can have this merged if you want! Thank you all for the huge opportunity ❤️

**Comment by Aslemammad** [comment]
I destroyed this branch, sorry, pushed to #164!

**Pull request closed without merging**
