### PR TITLE
fix(blob): remove slugify

### PR DESCRIPTION
**Pull request by quandabase**
Converting filename to a slug format is not necessary for uploading files to Cloudflare R2

### CODE REVIEW

**Comment by Atinux** [comment]
But isn't it safer anyway to slugify it @quandabase ?

**Comment by quandabase** [comment]
> But isn't it safer anyway to slugify it @quandabase ? What is your use case?

i just want the filename is exactly when i name it, so when download the file i just use that name, now i have to save the return path name to download the file because the filename is different

**Comment by Atinux** [comment]
What do you think of it @farnabaz ?

**Comment by farnabaz** [comment]
Preserving exact pathname in the `put` function sounds reasonable.  
As for safety, I think it is not a much of concern in blobs since it only uses to match file name. Cloudflare R2 buckets and Amazon S3 does not slugify paths either.

**Pull request merged**
