### PR TITLE
docs: improve drizzle seed example

### PR DESCRIPTION
**Pull request by redcodemohammed**
- Fixed a typo in the server tasks path

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks @redcodemohammed

**Comment by redcodemohammed** [comment]
Actually I just realized that I made a mistake 🥲
There should not be a role property on the user object

**Comment by Atinux** [comment]
No worries, fixed in https://github.com/nuxt-hub/core/commit/a8a8b01c0b2319b0b358332e5e940779e291c27b

**Comment by redcodemohammed** [comment]
Perfect 👌

**Comment by redcodemohammed** [comment]
Perfect 👌

**Pull request merged**
